# Generated by Django 2.2.6 on 2019-10-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20191009_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
